wip

diff --git a/src/main/resources/nextflow/templates/script3 b/src/main/resources/nextflow/templates/script3
--- a/src/main/resources/nextflow/templates/script3
+++ b/src/main/resources/nextflow/templates/script3
@@ -1,6 +1,9 @@
 #!/bin/bash
 
-# Print memory usage continuously until interrupted
-
+# Print memory usage
+{
     echo "Memory Usage"
-    free -m | grep "$variable"
+    free -m | grep "$variable" &&
+} || {
+  echo "error"
+}
